# Generated by Django 5.1.7 on 2025-05-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=100, verbose_name='Роль'),
        ),
    ]
